language: go
sudo: false
go:
  - 1.7
before_install:
  - go get -t -v ./...
install:
  - go build -ldflags="-X main.version=$TRAVIS_TAG" -v -o gitql ./cmd/...
script:
  - sh ./go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
